/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ALEJANDRO
 */
public class vista2 extends javax.swing.JPanel {

    /**
     * Creates new form vista1
     */
    public vista2() {
        initComponents();
        
        
foto1.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pinterest1.png")).getImage().getScaledInstance(350, 500, java.awt.Image.SCALE_SMOOTH)));

// 2. Forzar el centrado horizontal dentro del espacio del Label
foto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  
}
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        foto1 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        respuesta = new javax.swing.JTextField();
        respuesta1 = new javax.swing.JTextField();
        prestar = new javax.swing.JButton();
        paleta = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(706, 457));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(204, 0, 51));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(204, 0, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 40, 440));

        foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pinterest1.png"))); // NOI18N
        foto1.setMaximumSize(new java.awt.Dimension(1200, 1200));
        foto1.setPreferredSize(new java.awt.Dimension(1200, 1200));
        bg.add(foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 1, 370, 460));

        texto3.setBackground(new java.awt.Color(0, 51, 102));
        texto3.setFont(new java.awt.Font("STZhongsong", 0, 18)); // NOI18N
        texto3.setForeground(new java.awt.Color(0, 51, 102));
        texto3.setText("Folio Usuario:");
        bg.add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 190, 45));

        texto4.setFont(new java.awt.Font("STZhongsong", 0, 18)); // NOI18N
        texto4.setForeground(new java.awt.Color(0, 51, 102));
        texto4.setText("Libro ID:");
        bg.add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 158, 48));

        respuesta.setFont(new java.awt.Font("STZhongsong", 0, 14)); // NOI18N
        respuesta.addActionListener(this::respuestaActionPerformed);
        bg.add(respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 240, 40));

        respuesta1.addActionListener(this::respuesta1ActionPerformed);
        bg.add(respuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 240, 40));

        prestar.setBackground(new java.awt.Color(0, 51, 102));
        prestar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        prestar.setForeground(new java.awt.Color(255, 255, 255));
        prestar.setText("Realizar Prestamo");
        prestar.setBorder(null);
        prestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(prestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 200, 50));

        paleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paleta.png"))); // NOI18N
        paleta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 78, 1, 56, new java.awt.Color(0, 0, 0)));
        paleta.setMaximumSize(new java.awt.Dimension(300, 256));
        paleta.setMinimumSize(new java.awt.Dimension(300, 256));
        paleta.setPreferredSize(new java.awt.Dimension(300, 200));
        bg.add(paleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 290, 10));

        titulo3.setBackground(new java.awt.Color(0, 0, 0));
        titulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        titulo3.setForeground(new java.awt.Color(204, 0, 51));
        titulo3.setText("Panel Prestamo");
        bg.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestaActionPerformed

    private void respuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuesta1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel foto1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel paleta;
    private javax.swing.JButton prestar;
    private javax.swing.JTextField respuesta;
    private javax.swing.JTextField respuesta1;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel titulo3;
    // End of variables declaration//GEN-END:variables

    
}
