/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ALEJANDRO
 */
public class vista4 extends javax.swing.JPanel {

    /**
     * Creates new form vista1
     */
    public vista4() {
        initComponents();
        
        
foto2.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrada.png")).getImage().getScaledInstance(350, 500, java.awt.Image.SCALE_SMOOTH)));

// 2. Forzar el centrado horizontal dentro del espacio del Label
foto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  
}
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        foto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        respuesta5 = new javax.swing.JTextField();
        respuesta6 = new javax.swing.JTextField();
        devolvers = new javax.swing.JButton();
        paleta1 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(706, 457));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(204, 0, 51));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(204, 0, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 50, 440));

        foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrada.png"))); // NOI18N
        foto2.setMaximumSize(new java.awt.Dimension(1200, 1200));
        foto2.setPreferredSize(new java.awt.Dimension(1200, 1200));
        bg.add(foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 380, 490));

        texto3.setBackground(new java.awt.Color(0, 51, 102));
        texto3.setFont(new java.awt.Font("STZhongsong", 0, 18)); // NOI18N
        texto3.setForeground(new java.awt.Color(0, 51, 102));
        texto3.setText("Folio Usuario:");
        bg.add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, 45));

        texto4.setFont(new java.awt.Font("STZhongsong", 0, 18)); // NOI18N
        texto4.setForeground(new java.awt.Color(0, 51, 102));
        texto4.setText("Libro ID:");
        bg.add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 158, 48));

        respuesta5.setFont(new java.awt.Font("STZhongsong", 0, 14)); // NOI18N
        respuesta5.addActionListener(this::respuesta5ActionPerformed);
        bg.add(respuesta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 40));

        respuesta6.addActionListener(this::respuesta6ActionPerformed);
        bg.add(respuesta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 240, 40));

        devolvers.setBackground(new java.awt.Color(0, 51, 102));
        devolvers.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        devolvers.setForeground(new java.awt.Color(255, 255, 255));
        devolvers.setText("Devolver");
        devolvers.setBorder(null);
        devolvers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        devolvers.addActionListener(this::devolversActionPerformed);
        bg.add(devolvers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 200, 50));

        paleta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paleta.png"))); // NOI18N
        paleta1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 78, 1, 56, new java.awt.Color(0, 0, 0)));
        paleta1.setMaximumSize(new java.awt.Dimension(300, 256));
        paleta1.setMinimumSize(new java.awt.Dimension(300, 256));
        paleta1.setPreferredSize(new java.awt.Dimension(300, 200));
        bg.add(paleta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 10));

        titulo4.setBackground(new java.awt.Color(0, 0, 0));
        titulo4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        titulo4.setForeground(new java.awt.Color(204, 0, 51));
        titulo4.setText("Panel Devolución");
        bg.add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void respuesta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuesta5ActionPerformed

    private void respuesta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuesta6ActionPerformed

    private void devolversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolversActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_devolversActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton devolvers;
    private javax.swing.JLabel foto2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel paleta1;
    private javax.swing.JTextField respuesta5;
    private javax.swing.JTextField respuesta6;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables

    
}
