/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.biblioteca_digital.views1;

/**
 *
 * @author ALEJANDRO
 */
public class registroU1 extends javax.swing.JPanel {

    /**
     * Creates new form registroU1
     */
    public registroU1() {
        initComponents();
        imagen9.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen6.png")).getImage().getScaledInstance(280, 220, java.awt.Image.SCALE_SMOOTH)));

// 2. Forzar el centrado horizontal dentro del espacio del Label
imagen9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        forma3 = new javax.swing.JLabel();
        forma10 = new javax.swing.JTextField();
        forma4 = new javax.swing.JLabel();
        forma9 = new javax.swing.JTextField();
        forma5 = new javax.swing.JLabel();
        forma6 = new javax.swing.JLabel();
        forma7 = new javax.swing.JLabel();
        forma17 = new javax.swing.JPasswordField();
        forma20 = new javax.swing.JButton();
        forma16 = new javax.swing.JPasswordField();
        forma21 = new javax.swing.JLabel();
        forma15 = new javax.swing.JTextField();
        forma = new javax.swing.JLabel();
        forma14 = new javax.swing.JTextField();
        forma1 = new javax.swing.JLabel();
        forma13 = new javax.swing.JTextField();
        forma2 = new javax.swing.JLabel();
        forma12 = new javax.swing.JTextField();
        imagen9 = new javax.swing.JLabel();
        forma19 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        forma3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forma3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forma3.setText("Correo:");

        forma4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forma4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forma4.setText("Dirección:");

        forma9.setForeground(new java.awt.Color(153, 153, 153));
        forma9.addActionListener(this::forma9ActionPerformed);

        forma5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forma5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forma5.setText("Usuario:");

        forma6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forma6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forma6.setText("Constraseña:");

        forma7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forma7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forma7.setText("Confirmar Contraseña:");

        forma20.setBackground(new java.awt.Color(0, 51, 102));
        forma20.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        forma20.setForeground(new java.awt.Color(255, 255, 255));
        forma20.setText("Cancelar");
        forma20.setBorder(null);
        forma20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forma20.addActionListener(this::forma20ActionPerformed);

        forma16.addActionListener(this::forma16ActionPerformed);

        forma21.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        forma21.setForeground(new java.awt.Color(153, 0, 51));
        forma21.setText("Registro Nuevo Usuario");

        forma.setBackground(new java.awt.Color(255, 255, 255));
        forma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forma.setText("Cédula:");

        forma1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forma1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forma1.setText("Nombre:");

        forma2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forma2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forma2.setText("Apellido:");

        forma12.addActionListener(this::forma12ActionPerformed);

        imagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen6.png"))); // NOI18N

        forma19.setBackground(new java.awt.Color(0, 51, 102));
        forma19.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        forma19.setForeground(new java.awt.Color(255, 255, 255));
        forma19.setText("Registrar");
        forma19.setBorder(null);
        forma19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forma19.addActionListener(this::forma19ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(forma21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(imagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(forma19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(forma7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forma17, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(forma20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(forma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(forma9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(forma1)
                        .addGap(19, 19, 19)
                        .addComponent(forma10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(forma2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(forma12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(forma3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(forma13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(forma4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(forma14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(forma5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(forma15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(forma6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(forma16, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(forma21, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(imagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma)
                    .addComponent(forma9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma1)
                    .addComponent(forma10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma2)
                    .addComponent(forma12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma3)
                    .addComponent(forma13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma4)
                    .addComponent(forma14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma5)
                    .addComponent(forma15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma6)
                    .addComponent(forma16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma7)
                    .addComponent(forma17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forma19, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(forma20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void forma9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forma9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forma9ActionPerformed

    private void forma20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forma20ActionPerformed
 
    }//GEN-LAST:event_forma20ActionPerformed

    private void forma16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forma16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forma16ActionPerformed

    private void forma12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forma12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forma12ActionPerformed

    private void forma19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forma19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forma19ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forma;
    private javax.swing.JLabel forma1;
    private javax.swing.JTextField forma10;
    private javax.swing.JTextField forma12;
    private javax.swing.JTextField forma13;
    private javax.swing.JTextField forma14;
    private javax.swing.JTextField forma15;
    private javax.swing.JPasswordField forma16;
    private javax.swing.JPasswordField forma17;
    private javax.swing.JButton forma19;
    private javax.swing.JLabel forma2;
    private javax.swing.JButton forma20;
    private javax.swing.JLabel forma21;
    private javax.swing.JLabel forma3;
    private javax.swing.JLabel forma4;
    private javax.swing.JLabel forma5;
    private javax.swing.JLabel forma6;
    private javax.swing.JLabel forma7;
    private javax.swing.JTextField forma9;
    private javax.swing.JLabel imagen9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
